### ISSUE TITLE
商品マスター画面で検索結果表示は正しくないです

### ISSUE THREAD

**Issue by trebla-on** [EC-CUBE/ec-cube#1898]
商品管理商品マスター画面で検索結果表示は正しくないです
１．管理画面の「ホーム」画面でショップ状況の「在庫切れ商品」を押す->商品マスターへ移動する
２．商品マスターの結果の中に商品を表示します
３．「 非公開」リンク押すと商品が表示しない
４．「在庫なし」リンク押すと商品表示しないです　　　// 問題はここです、在庫なしのに商品表示しない
５．また「公開 」押すと先の商品表示します
６．「在庫なし」リンク押すと商品表示します

**Comment by Yangsin** [comment]
こちら問題の状態と期待する結果を、もうすこし教えていただけますでしょうか。

**Comment by lqdung-lockon** [comment]
Hi @trebla-on -san, @Yangsin -san,
It consists of two issues:
1. Product non stock shows is incorrect (because of the admin page, it is calculated based on the the number of product classes).
2. Change the status of the search for products at the results is incorrect. (LVN team has announced in previous projects - Increasing the coverage of the project ec-cube).

The bugs will fixed in [this](https://github.com/EC-CUBE/ec-cube/compare/master...eccubevn:bug_fix_%231898)

**Comment by trebla-on** [comment]
@Yangsin 
> こちら問題の状態と期待する結果を、もうすこし教えていただけますでしょうか。
説明は正しくなかったです、問題はステップ「４」の時です
４．「在庫なし」リンク押すと商品表示しないです
在庫なしのに商品表示しない。

**Comment by ryo-endo** [comment]
#1968で対応完了しました。
